permutation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('randomword.urls')),
    path('admin/', admin.site.urls),
]

randomword/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.form_view, name="permutation")
]

randomword/models.py
from django.db import models

# Create your models here.

randomword/forms.py
from django import forms


class PermutationForm(forms.Form):
    # word permutation form
    word = forms.CharField(label="Enter word", max_length=255, required=True)

randomword/views.py
from django.shortcuts import render
from .forms import PermutationForm
from itertools import permutations, combinations
import string

# TODO // algorithm is slow (Improve on performance)
def perform_calculation(word):
    main_list = []
    length = range(len(word))
    for i in length:
        # TODO // implement custom/self permutation algorithm
        main_list += list(permutations(word, i+1))
    return main_list

"""
@ Depricated function:: Just for recall.
========================================
# def swapitem(first, last):
#     if len(first) > len(last):
#         return first
#     return last
"""

def form_view(request):
    # display on get request
    if request.method == 'GET':
        form = PermutationForm()
    # display on post request
    elif request.method == 'POST':
        form = PermutationForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data['word']
            word =  sorted(perform_calculation(word))
            return render(request, 'form.html', {'form': form, 'word': word, 'count': len(word)})
    return render(request, 'form.html', {'form': form})

templates/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <style>
        #result {
            visibility: hidden;
        }
        #box{
            visibility: hidden;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Permutaion Form</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark rgba-blue-strong justify-content-center animated wobble"
    style="font-family: 'Fira Sans', sans-serif;">
    <a class="navbar-brand animated fadeInDown" href="#">Word Permutation and Combination Sorting App</a>
</nav>
<div class="container">
    <div class="row mb-5">
        {% if not word %}
        <div class="col-sm-12 col-md-6 offset-3 mt-5">
            <form method="POST" class="animated flipInY">
                {% csrf_token %}
                <div class="form-group text-white text-uppercase">
                    {{form}}
                </div>
                <button id="submit" class="btn btn-sm btn-primary">GO</button>
            </form>
        </div>
        {% else %}
        <div class="col-sm-12 col-md-6 mt-5">
            <form method="POST" class="animated flipInY" style="font-family: 'Fira Sans', sans-serif;">
                {% csrf_token %}
                <div class="form-group text-white text-uppercase">
                    {{form}}
                </div>
                <button id="submit" class="btn btn-sm btn-primary">GO</button>
            </form>
        </div>
        {% endif %}
        <div class=" col-sm-8 col-md-4 offset-md-2 mt-5">
            <!-- Results -->
            {% if word %}
            <h5 class="text-white">Possible outcomes: {{count}}</h5>
            <div id="box" class="border rounded animated bounce shadow-lg border border-primary" style="position: relative; height: 400px; margin-top: .5rem; overflow: auto" data-spy="scroll"
                data-target="#navbar-example2" data-offset="0">
                <ul class="list-group list-group-flush" id="result">
                    {% for item in word %}
                    <li class="list-group-item list-group-item-action list-group-primary"><strong>{{item}}</strong></li>
                    {% endfor %}
                </ul>
            </div>
            {% else %} {% endif %}
        </div>
    </div>
</div>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/mdb.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#id_word').addClass('form-control');

            function showResult(){
                $('#result').css('visibility', 'visible');
                $('#result').addClass('animated slideInLeft');
                $('#box').css('visibility', 'visible');
            }
            setTimeout(showResult, 2000);
        });
    </script>

</body>
</html>